module.exports = {
	"logo": require('./logo.png'),
	"splash": require('./splash.png'),
	"menu": require('./hamburger-dark.png'),
	"info": require('./info-dark.png'),

	"first": require('./first.png'),
	"second": require('./second.png'),

	"NE": require('./no-effect.png'),
	"DG": require('./disorganized.png'),
	"1": require('./1.png'),
	"2": require('./2.png'),
	"3": require('./3.png'),
	"4": require('./4.png'),
	"5": require('./5.png'),

	"refreshButton": require('./refresh-dark.png'),
	"prevButton":	require('./ic_action_previous_item.png'),
	"nextButton": require('./ic_action_next_item.png'),

	"afrika": require('./afrika.jpg'),
	"ardennes": require('./ardennes.jpg'),
	"bastogne": require('./bastogne.jpg'),
	"crusader": require('./crusader.jpg'),
	"driveonparis": require('./driveonparis.jpg'),
	"dop": require('./dop.jpg'),
	"fallschirmjaeger": require('./fallschirmjaeger.jpg'),
	"fsj": require('./fsj.jpg'),
	"gazala": require('./gazala.jpg'),
	"guadalajara": require('./guadalajara.jpg'),
	"heightsofcourage": require('./heightsofcourage.jpg'),
	"operationmichael": require('./operationmichael.png'),
	"stalingradpocket": require('./stalingradpocket.jpg'),
	"themightyendeavor": require('./themightyendeavor.jpg'),
	"victory": require('./victory.jpg'),
	"yomkippur": require('./yomkippur.jpg'),
};
