import { Icons } from 'react-native-nub';

module.exports = {
	"logo": require('./logo.png'),
	"splash": require('./splash.png'),
	"menu": Icons['menu-dark'],
	"info": Icons['info-dark'],
	"refresh": Icons['refresh-dark'],

	"NE": require('./no-effect.png'),
	"DG": require('./disorganized.png'),
	"REDUCED": require('./reduced.png'),
	"1": require('./1.png'),
	"2": require('./2.png'),
	"3": require('./3.png'),
	"4": require('./4.png'),
	"5": require('./5.png'),

	"germany": require('./germany.png'),
	"axis-east": require('./axis-east.png'),
	"axis-south": require('./axis-south.png'),
	"allies-south": require('./allies-south.png'),
	"allies-west": require('./allies-west.png'),
	"us-uk": require('./us-uk.png'),
	"usa": require('./usa.png'),
	"netherlands": require('./netherlands.png'),
	"ussr": require('./ussr.png'),
	"imperial-germany": require('./imperial-germany.png'),
	"france-uk": require('./france-uk.png'),
	"egypt": require('./egypt.png'),
	"syria": require('./syria.png'),
	"israel": require('./israel.png'),

	"afrika": require('./afrika.jpg'),
	"ardennes": require('./ardennes.jpg'),
	"bastogne": require('./bastogne.jpg'),
	"crusader": require('./crusader.jpg'),
	"driveonparis": require('./driveonparis.jpg'),
	"dop": require('./dop.jpg'),
	"fallschirmjaeger": require('./fallschirmjaeger.jpg'),
	"fsj": require('./fsj.jpg'),
	"gazala": require('./gazala.jpg'),
	"guadalajara": require('./guadalajara.jpg'),
	"heightsofcourage": require('./heightsofcourage.jpg'),
	"operationmichael": require('./operationmichael.png'),
	"stalingradpocket": require('./stalingradpocket.jpg'),
	"themightyendeavor": require('./themightyendeavor.jpg'),
	"victory": require('./victory.jpg'),
	"yomkippur": require('./yomkippur.jpg')
};
