module.exports = {
    TOAST: 'TOAST',
    SET_CURRENT: 'SET_CURRENT',
    SET_TURN: 'SET_TURN',
    SET_PHASE: 'SET_PHASE',    
    SET_PLAYER: 'SET_PLAYER',
    SET_INITIATIVE: 'SET_INITIATIVE',
    SET_VICTORY: 'SET_VICTORY'
};
