module.exports = {
	"logo": require('../res/logo.png'),
	"splash": require('../res/splash.png'),
	"menu": require('../res/hamburger-dark.png'),
	"info": require('../res/info-dark.png'),

	"first": require('../res/first.png'),
	"second": require('../res/second.png'),

	"NE": require('../res/no-effect.png'),
	"DG": require('../res/disorganized.png'),
	"REDUCED": require('../res/reduced.png'),
	"1": require('../res/1.png'),
	"2": require('../res/2.png'),
	"3": require('../res/3.png'),
	"4": require('../res/4.png'),
	"5": require('../res/5.png'),

	"refreshButton": require('../res/refresh-dark.png'),
	"prevButton":	require('../res/ic_action_previous_item.png'),
	"nextButton": require('../res/ic_action_next_item.png'),
	"checked": require('../res/checked_checkbox.png'),
	"unchecked": require('../res/unchecked_checkbox.png'),

	"afrika": require('../res/afrika.jpg'),
	"ardennes": require('../res/ardennes.jpg'),
	"bastogne": require('../res/bastogne.jpg'),
	"crusader": require('../res/crusader.jpg'),
	"driveonparis": require('../res/driveonparis.jpg'),
	"dop": require('../res/dop.jpg'),
	"fallschirmjaeger": require('../res/fallschirmjaeger.jpg'),
	"fsj": require('../res/fsj.jpg'),
	"gazala": require('../res/gazala.jpg'),
	"guadalajara": require('../res/guadalajara.jpg'),
	"heightsofcourage": require('../res/heightsofcourage.jpg'),
	"operationmichael": require('../res/operationmichael.png'),
	"stalingradpocket": require('../res/stalingradpocket.jpg'),
	"themightyendeavor": require('../res/themightyendeavor.jpg'),
	"victory": require('../res/victory.jpg'),
	"yomkippur": require('../res/yomkippur.jpg')
};
